"""Deterministic maintenance artifacts for ClipWiki note directories."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from clipwiki.markdown_sections import title_from_markdown
from clipwiki.note_index import build_note_index, memory_dir
from clipwiki.validation import validate_note_file
from clipwiki.wiki_graph import LinkGraph, build_link_graph, visible_note_paths

WIKI_INDEX_FILENAME = "wiki_index.md"
CHANGE_LOG_FILENAME = "change_log.md"
LINK_GRAPH_FILENAME = "link_graph.json"
LINT_REPORT_FILENAME = "lint_report.json"


@dataclass(slots=True)
class LintIssue:
    """One deterministic wiki health issue."""

    type: str
    message: str
    path: str | None = None


@dataclass(slots=True)
class LintReport:
    """Serializable wiki health report."""

    pages_checked: int
    issues: list[LintIssue]

    def to_dict(self) -> dict[str, Any]:
        return {"pages_checked": self.pages_checked, "issues": [asdict(issue) for issue in self.issues]}


@dataclass(slots=True)
class MaintenanceArtifacts:
    """Files and metadata generated by a maintenance refresh."""

    wiki_index_path: Path
    change_log_path: Path
    link_graph_path: Path
    lint_report_path: Path
    pages_checked: int
    issue_count: int


def refresh_wiki_maintenance(notes_root: Path) -> MaintenanceArtifacts:
    """Rebuild deterministic wiki management artifacts for visible notes."""

    notes_root = notes_root.resolve()
    index_payload = build_note_index(notes_root)
    graph = build_link_graph(notes_root)
    lint_report = build_lint_report(notes_root, graph=graph)

    index_dir = memory_dir(notes_root)
    index_dir.mkdir(parents=True, exist_ok=True)
    wiki_index_path = index_dir / WIKI_INDEX_FILENAME
    change_log_path = index_dir / CHANGE_LOG_FILENAME
    link_graph_path = index_dir / LINK_GRAPH_FILENAME
    lint_report_path = index_dir / LINT_REPORT_FILENAME

    wiki_index_path.write_text(render_wiki_index(index_payload), encoding="utf-8")
    link_graph_path.write_text(json.dumps(graph.to_dict(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    lint_report_path.write_text(json.dumps(lint_report.to_dict(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    return MaintenanceArtifacts(
        wiki_index_path=wiki_index_path,
        change_log_path=change_log_path,
        link_graph_path=link_graph_path,
        lint_report_path=lint_report_path,
        pages_checked=lint_report.pages_checked,
        issue_count=len(lint_report.issues),
    )


def record_ingest_event(
    notes_root: Path,
    *,
    status: str,
    action: str,
    note_path: Path | None,
    title: str,
    reason: str,
    llm_backend_calls: int = 0,
    llm_total_tokens: int = 0,
    llm_estimated_cost_usd: float = 0.0,
    refresh: bool = True,
) -> MaintenanceArtifacts | None:
    """Append an ingest log entry and optionally refresh maintenance artifacts."""

    notes_root = notes_root.resolve()
    append_change_log(
        notes_root,
        status=status,
        action=action,
        note_path=note_path,
        title=title,
        reason=reason,
        llm_backend_calls=llm_backend_calls,
        llm_total_tokens=llm_total_tokens,
        llm_estimated_cost_usd=llm_estimated_cost_usd,
    )
    if refresh and status in {"created", "updated"}:
        return refresh_wiki_maintenance(notes_root)
    return None


def append_change_log(
    notes_root: Path,
    *,
    status: str,
    action: str,
    note_path: Path | None,
    title: str,
    reason: str,
    llm_backend_calls: int = 0,
    llm_total_tokens: int = 0,
    llm_estimated_cost_usd: float = 0.0,
) -> Path:
    """Append a compact ingest event to the internal change log."""

    index_dir = memory_dir(notes_root)
    index_dir.mkdir(parents=True, exist_ok=True)
    log_path = index_dir / CHANGE_LOG_FILENAME
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    relative_note = _relative_or_absolute(note_path, notes_root) if note_path is not None else "not written"
    entry = "\n".join(
        [
            f"## [{timestamp}] {status} | {action}",
            "",
            f"- Title: {title or '-'}",
            f"- Note: `{relative_note}`",
            f"- Reason: {reason or '-'}",
            f"- LLM backend calls: {llm_backend_calls}",
            f"- LLM total tokens: {llm_total_tokens}",
            f"- LLM estimated cost: ${llm_estimated_cost_usd:.6f}",
            "",
        ]
    )
    existing = log_path.read_text(encoding="utf-8") if log_path.exists() else "# ClipWiki Change Log\n"
    separator = "" if existing.endswith("\n") else "\n"
    log_path.write_text(existing + separator + entry, encoding="utf-8")
    return log_path


def read_change_log(notes_root: Path, *, last: int | None = None) -> list[str]:
    """Read change log entries, optionally returning the last N entries."""

    log_path = memory_dir(notes_root) / CHANGE_LOG_FILENAME
    if not log_path.exists():
        return []
    entries: list[str] = []
    current: list[str] = []
    for line in log_path.read_text(encoding="utf-8").splitlines():
        if line.startswith("## ["):
            if current:
                entries.append("\n".join(current).strip())
            current = [line]
        elif current:
            current.append(line)
    if current:
        entries.append("\n".join(current).strip())
    return entries[-last:] if last else entries


def build_lint_report(notes_root: Path, *, graph: LinkGraph | None = None) -> LintReport:
    """Check visible notes for link and Markdown health issues."""

    graph = graph or build_link_graph(notes_root)
    issues: list[LintIssue] = []
    for broken in graph.broken_links:
        issues.append(LintIssue(type="broken-link", message=f"{broken.source} -> [[{broken.target}]]", path=broken.source))
    for orphan in graph.orphans:
        issues.append(LintIssue(type="orphan", message=f"{orphan} has no inbound wikilinks", path=orphan))

    for path in visible_note_paths(notes_root):
        relative_path = path.resolve().relative_to(notes_root.resolve()).as_posix()
        markdown = path.read_text(encoding="utf-8")
        if not markdown.strip():
            issues.append(LintIssue(type="empty-page", message=relative_path, path=relative_path))
            continue
        validation = validate_note_file(markdown)
        for issue in validation.issues:
            issues.append(LintIssue(type="note-validation", message=issue, path=relative_path))

    return LintReport(pages_checked=len(graph.pages), issues=issues)


def render_wiki_index(index_payload: dict[str, Any]) -> str:
    """Render a deterministic internal wiki index from the note index payload."""

    grouped: dict[str, list[dict[str, Any]]] = {}
    for file_record in index_payload.get("files", []):
        path = str(file_record.get("path", ""))
        if not path:
            continue
        category = Path(path).parts[0] if len(Path(path).parts) > 1 else "root"
        grouped.setdefault(category, []).append(file_record)

    lines = [
        "# ClipWiki Wiki Index",
        "",
        "This internal index is generated deterministically from visible Markdown notes.",
        "",
    ]
    for category in sorted(grouped):
        lines.extend([f"## {category}", ""])
        for file_record in sorted(grouped[category], key=lambda item: str(item.get("path", ""))):
            path = str(file_record.get("path", ""))
            title = str(file_record.get("title", "")) or Path(path).stem
            summary = str(file_record.get("summary", "")).strip()
            lines.append(f"- [[{path}]] — {title}")
            if summary:
                lines.append(f"    - {summary[:220]}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def note_title(path: Path) -> str:
    """Return the first H1 title from a note path."""

    return title_from_markdown(path.read_text(encoding="utf-8"), fallback=path.stem)


def _relative_or_absolute(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return str(path)
